pdfs_sl: pdfs_sl.cpp
	clang++ -Wall -Wextra -O2 -o pdfs_sl pdfs_sl.cpp `root-config --cflags --glibs ` -lSpectrum

pdfs_dl: pdfs_dl.cpp
	clang++ -Wall -Wextra -O2 -o pdfs_dl pdfs_dl.cpp `root-config --cflags --glibs ` -lSpectrum