# model_name: 'BinaryClassifier_SL_DeepResidualBlockExtraFeatures'
model_name: 'test2'
training_directory: '/home/artem/Desktop/CMS/models/classifiers'

hyperparameters:
  training_parity: 0
  validation_parity: 1
  test_parity: 2
  use_extra_branches: True
  num_hidden_layers: 3
  dropout: 0.2
  batch_size: 8192
  epochs: 50
  learning_rate: 0.0003

base_branches:
  - 'other_jet1_mass'
  - 'deta_bb'
  - 'dPhi_jet1_jet2'
  - 'other_jet1_btagPNetB'
  # - 'nSelBtag_fatjets' 
  - 'dPhi_MET_dibjet'
  # - 'fatbjet_eta' 
  - 'other_jet2_mass'
  - 'other_jet2_pt'
  - 'other_jet1_pt'
  - 'lep1_mass'
  - 'bjet2_btagPNetB'
  - 'other_jet2_eta'
  - 'bjet1_phi'
  - 'MT2_bb'  
  - 'bjet2_pt' 
  # - 'fatbjet_phi'
  - 'other_jet2_btagPNetB'
  - 'bjet1_mass'
  - 'dphi_bb'
  - 'bjet2_mass'
  - 'PuppiMET_pt' 
  - 'other_jet2_phi'
  - 'other_jet1_phi' 
  - 'bjet1_eta'
  # - 'fatbjet_mass' 
  - 'bb_mass_PNetRegPtRawCorr_PNetRegPtRawCorrNeutrino'
  - 'other_jet1_eta'
  # - 'fatbjet_particleNetWithMass_HbbvsQCD'
  - 'SingleLep_DeepHME_mass'
  - 'nSelBtag_jets'
  - 'Lep1Jet1Jet2_mass'
  - 'bjet2_eta'
  - 'PuppiMET_phi'
  # - 'fatbjet_particleNet_XbbVsQCD'
  # - 'fatbjet_mass_PNetCorr'
  - 'SingleLep_DeepHME_mass_error'
  - 'CosTheta_bb'
  - 'bjet1_pt'
  - 'MT'
  # - 'fatbjet_pt'
  - 'bjet2_phi' 
  # - 'fatbjet_msoftdrop'
  - 'lep1_phi'
  - 'dR_dibjet'
  - 'HT'
  - 'lep1_pt'
  - 'bjet1_btagPNetB'

extra_branches:
  - 'light_jet2_mass'
  - 'light_jet2_phi'
  - 'light_jet1_phi'
  - 'dphi_hadT_hadW'
  # - 'fatbjet_muEF'
  - 'min_dphi_b_hadW'
  - 'dphi_Hbb_Hww'
  - 'mT_Hww'
  - 'min_dphi_bl'
  - 'lep2_pt'
  - 'm_Hbb'
  - 'lep2_mass'
  # 'fatbjet_neEmEF'
  - 'pT_Hbb'
  - 'min_dphi_b_lepW' 
  - 'mass_hadT'
  - 'light_jet2_pt'
  - 'light_jet2_btagPNetB'
  - 'light_jet1_mass'
  - 'light_jet1_eta'
  - 'pT_lepT'
  # 'fatbjet_neMultiplicity'
  - 'min_dR_b_hadW'
  - 'ratio_pT_hadT_const' 
  - 'fatbjet_tau3' 
  - 'light_jet1_btagPNetB'
  - 'pTtoE_ratio_Hww'
  - 'm_Hww'
  - 'dphi_hadW_lepW' 
  - 'm_hadW'
  - 'dR_hadW_lepW' 
  - 'dR_Hbb_Hww'
  - 'light_jet1_pt' 
  # - 'fatbjet_tau1' 
  - 'mT_lepT'
  # - 'fatbjet_tau2' 
  - 'mT_hadT'
  - 'deta_leadBjet_hadW'
  - 'pT_lepW'
  - 'lep2_eta'
  - 'dR_hadW_l'
  - 'm_b_lepT'
  - 'min_dR_b_lepW'
  - 'pT_hadW'
  - 'deta_hadT_hadW'
  - 'dphi_hadW_l'
  - 'min_dR_bl'
  - 'mT_lepW'
  - 'lep2_phi'
  # - 'fatbjet_neHEF'
  - 'pT_Hww'
  - 'pT_hadT'
  # - 'fatbjet_tau4'
  - 'dR_leadBjet_hadW'
  - 'pTtoE_ratio_HH'
  # 'fatbjet_nConstituents'
  - 'light_jet2_eta'
  - 'dphi_leadBjet_hadW'
  - 'pTtoE_ratio_Hbb'
  - 'dR_hadT_hadW'
  - 'mT_hadW'