tree_name: Events

objects:
  input_objects:
    centralJet:
      target_shape: 10
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
        - 'btagPNetB'
        - 'btagPNetCvB'
        - 'btagPNetCvL'
        - 'btagPNetCvNotB'
        - 'btagPNetQvG'
        - 'PNetRegPtRawCorr'
        - 'PNetRegPtRawCorrNeutrino'
        - 'PNetRegPtRawRes'
    SelectedFatJet:
      target_shape: 3
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
        - 'particleNet_QCD'
        - 'particleNet_XbbVsQCD'
        - 'particleNetWithMass_QCD'
        - 'particleNetWithMass_HbbvsQCD'
        - 'particleNet_massCorr'
    lep1:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
    lep2:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
    met:
      target_shape: 1
      kinematics_output_format: ['px', 'py']
      branches_to_load:
        - 'pt'
        - 'phi'

  target_objects:
    genHVV:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
    genHbb:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'

  extra_objects:
    genb1:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
    genb2:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'

# loaded as they are in input file
auxilliary_branches:
  - 'event'
  - 'sample_type'
  - 'X_mass'
  - 'ncentralJet'
  - 'nSelectedFatJet'
  - 'lep1_legType'
  - 'lep1_gen_kind'
  - 'lep2_legType'
  - 'lep2_gen_kind'
  - 'genV1prod1_pt'
  - 'genV2prod1_pt'

selection_config: 
  gen_level: True
  reco_level: True
  gen_reco_matching: True
  signal_region: False
plot_cutflow: True
plot_dir: 'cutflow_plots'
use_percentages: False
use_topology: mixed
