file_names: [../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_1000/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_1200/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_1400/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_1600/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_1800/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_2000/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_250/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_2500/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_260/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_270/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_280/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_300/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_3000/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_350/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_4000/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_450/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_5000/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_550/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_600/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_650/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_700/nano_0.root,
  ../train_data/Run3_2022/GluGlutoBulkGravitontoHHto2B2Vto2B2L2Nu_M_800/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_1000/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_1200/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_1400/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_1600/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_1800/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_2000/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_250/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_2500/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_260/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_270/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_280/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_300/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_3000/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_350/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_4000/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_450/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_5000/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_550/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_600/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_650/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_700/nano_0.root,
  ../train_data/Run3_2022/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M_800/nano_0.root]
  # - nano_0.root
tree_name: Events

objects:
  input_objects:
    centralJet:
      target_shape: 10
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      compute_num_valid: True
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
        - 'btagPNetB'
        - 'btagPNetCvB'
        - 'btagPNetCvL'
        - 'btagPNetCvNotB'
        - 'btagPNetQvG'
        - 'PNetRegPtRawCorr'
        - 'PNetRegPtRawCorrNeutrino'
        - 'PNetRegPtRawRes'
    SelectedFatJet:
      target_shape: 3
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      compute_num_valid: True
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
        - 'particleNet_QCD'
        - 'particleNet_XbbVsQCD'
        - 'particleNetWithMass_QCD'
        - 'particleNetWithMass_HbbvsQCD'
        - 'particleNet_massCorr'
    lep1:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      compute_num_valid: False
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
    lep2:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      compute_num_valid: False
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
    met:
      target_shape: 1
      kinematics_output_format: ['px', 'py']
      compute_num_valid: False
      branches_to_load:
        - 'pt'
        - 'phi'

  target_objects:
    genHVV:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      compute_num_valid: False
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
    genHbb:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      compute_num_valid: False
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'

  extra_objects:
    genb1:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      compute_num_valid: False
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'
    genb2:
      target_shape: 1
      kinematics_output_format: ['px', 'py', 'pz', 'E']
      compute_num_valid: False
      branches_to_load:
        - 'pt'
        - 'eta'
        - 'phi'
        - 'mass'

# loaded as they are in input file
auxilliary_branches:
  - 'event'
  - 'sample_type'
  - 'X_mass'
  - 'ncentralJet'
  - 'nSelectedFatJet'
  - 'lep1_legType'
  - 'lep1_gen_kind'
  - 'lep2_legType'
  - 'lep2_gen_kind'

apply_selections: True
plot_cutflow: False
plot_dir: 'cutflow_plots'
use_percentages: False
use_topology: mixed
